### ISSUE TITLE
Error adding the cartridge, public key file missing

### ISSUE THREAD

**Issue by hkhako** [dreamfactorysoftware/openshift-dreamfactory-cartridge#3] opened 2016-01-21 06:42 UTC
It gives me error when I try to install it on an OpenShift free account.  The error output says it is missing public key files:

Warning: file_put_contents(/composer/.composer//keys.dev.pub): failed to open stream: No such file or directory in - on line 381

Warning: file_put_contents(/composer/.composer//keys.tags.pub): failed to open stream: No such file or directory in - on line 398
Downloading...

Warning: openssl_verify(): supplied key param cannot be coerced into a public key in - on line 472

Warning: openssl_free_key() expects parameter 1 to be resource, boolean given in - on line 473
Signature mismatch, could not verify the phar file integrity
Unable to complete the requested operation due to: An invalid exit code (157) was returned from the server ex-std-node628.prod.rhcloud.com.  This indicates an unexpected problem during the execution of your request.

**Comment by DamonV** [comment] 2016-01-21 17:15
I had the same problem.

**Comment by drewpearce** [comment] 2016-01-21 18:49
filed a bug report with the dev team

**Comment by crearis** [comment] 2016-01-27 12:13
I had the same problem

**Comment by drewpearce** [comment] 2016-01-27 15:08
Just a quick update. We've got a developer working on this. No ETA, but hopefully not long.

**Comment by crearis** [comment] 2016-01-27 15:15
Hi,

upates from me as well ..
this is great … meanwhile I managed to open phpMyAdmin … and there were users setup, name = phproot
problem here is: the phproot-user-name has not email format

and: maybe I should use a different browser for the initial steps than firefox?

thanks

Hans

Von: drewpearce [mailto:notifications@github.com]
Gesendet: Mittwoch, 27. Januar 2016 16:08
An: dreamfactorysoftware/openshift-dreamfactory-cartridge openshift-dreamfactory-cartridge@noreply.github.com
Cc: Hans Doenitz hans.doenitz@dasei.eu
Betreff: Re: [openshift-dreamfactory-cartridge] Error adding the cartridge, public key file missing (#3)

Just a quick update. We've got a developer working on this. No ETA, but hopefully not long.

**Comment by chris-gunawardena** [comment] 2016-01-28 14:35
Hi all, 

This was caused by a recent update to the composer install script, should be fixed now.

**Closed as completed by chris-gunawardena** 2016-01-28 14:35 UTC
Labels: bug

**Comment by crearis** [comment] 2016-01-28 14:57
thanks, that's really great new, I'll try it out soon!!

**Comment by DamonV** [comment] 2016-02-03 12:36
thanks, works perfectly
